# Generated by Django 3.0.6 on 2020-05-31 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customuserapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='age',
            field=models.IntegerField(default=0),
        ),
    ]
