# Generated by Django 3.0.6 on 2020-05-19 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customuserapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='display_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
